export const movies = {
  movies: [
  {
    id: "1",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "After Everything",
    overview: "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
    release_date: "2023-09-13",
  },
  {
    id: "2",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Retribution",
    overview: "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
    release_date: "2023-08-23",
  },
  {
    id: "3",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Barbie",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    release_date: "2023-07-19",
    },
  {
    id: "4",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "After Everything",
    overview: "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
    release_date: "2023-09-13",
    
  },
  {
    id: "5",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Retribution",
    
    overview: "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
    release_date: "2023-08-23",
  },
  {
    id: "6",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Barbie",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    release_date: "2023-07-19",
    },
  {
    id: "7",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "After Everything",
    overview: "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
    release_date: "2023-09-13",
  },
  {
    id: "8",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Retribution",
    overview: "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
    release_date: "2023-08-23",  
  },
  {
    id: "9",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Barbie",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    release_date: "2023-07-19",
    },
  {
    id: "10",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "After Everything",
    overview: "Besieged by writer’s block and the crushing breakup with Tessa, Hardin travels to Portugal in search of a woman he wronged in the past – and to find himself. Hoping to win back Tessa, he realizes he needs to change his ways before he can make the ultimate commitment.",
    release_date: "2023-09-13",
  },
  {
    id: "762430",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Retribution",
    overview: "When a mysterious caller puts a bomb under his car seat, Matt Turner begins a high-speed chase across the city to complete a specific series of tasks. With his kids trapped in the back seat and a bomb that will explode if they get out of the car, a normal commute becomes a twisted game of life or death as Matt follows the stranger's increasingly dangerous instructions in a race against time to save his family.",
    release_date: "2023-08-23",
  },
  {
    id: "346698",
    adult: false,
    poster_path: '/uQxjZGU6rxSPSMeAJPJQlmfV3ys.jpg',
    title: "Barbie",
    overview: "Barbie and Ken are having the time of their lives in the colorful and seemingly perfect world of Barbie Land. However, when they get a chance to go to the real world, they soon discover the joys and perils of living among humans.",
    release_date: "2023-07-19",
  }]
};
