version: "3"
services:
  server:
    build: ./GraphQL
    container_name: graphQL_c
    ports:
      - '4000:4000'
    volumes:
      - ./GraphQL:/app
      - ./app/node_modules:/app/node_modules
  client:
    build: ./client
    container_name: client_c
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./app/node_modules:/app/node_modules
    stdin_open: true
    tty: true

#docker run -d -p 3000:3000 your-image-name
